use patchwright_core::action::Action;
use patchwright_core::agent::{Agent, SolveStatus};
use patchwright_core::error::{PatchwrightError, Result};
use patchwright_core::policy::Policy;
use patchwright_core::traits::ModelProvider;
use patchwright_core::types::{ModelRequest, ModelResponse, Patch, TaskSpec, VerificationStatus};
use patchwright_exec_local::{GitWorktreeSandbox, LocalExecution};
use patchwright_index::BasicIndexer;
use patchwright_lang_rust::RustAdapter;
use patchwright_test_support::TempRepo;
use patchwright_verify::PlanVerifier;
use std::fs;
use std::path::Path;
use std::process::Command;

struct ScriptedModel {
    actions: Vec<Action>,
}

impl ModelProvider for ScriptedModel {
    fn propose_action(&mut self, _request: ModelRequest) -> Result<ModelResponse> {
        let Some(action) = self.actions.first().cloned() else {
            return Err(PatchwrightError::Model("script exhausted".to_owned()));
        };
        self.actions.remove(0);
        Ok(ModelResponse { action })
    }
}

#[test]
fn scripted_model_applies_verified_patch_inside_sandbox() -> Result<()> {
    let repo = tiny_broken_rust_repo("verified-patch-accepted");
    let source_lib_path = repo.root().join("src/lib.rs");
    let original_source = fs::read_to_string(&source_lib_path)?;
    let sandbox = GitWorktreeSandbox::create(repo.root())?;
    let sandbox_root = sandbox.root().to_path_buf();

    let model = ScriptedModel {
        actions: vec![Action::ApplyPatch(Patch {
            unified_diff: correct_add_patch(),
        })],
    };
    let mut agent = Agent::builder()
        .model(model)
        .execution(LocalExecution::new(&sandbox_root))
        .language_adapter(RustAdapter::default())
        .indexer(BasicIndexer::new(&sandbox_root))
        .verifier(PlanVerifier)
        .policy(cargo_policy())
        .max_steps(5)
        .try_build()?;

    let report = agent.solve(TaskSpec::code_change(
        sandbox_root.clone(),
        "Fix the failing add test with the smallest correct patch.",
    ))?;

    assert_eq!(report.status, SolveStatus::Accepted);
    assert_eq!(report.attempts.len(), 1);
    assert_eq!(
        report.attempts[0].verification.status,
        VerificationStatus::Accepted
    );
    assert_eq!(fs::read_to_string(source_lib_path)?, original_source);
    assert!(fs::read_to_string(sandbox_root.join("src/lib.rs"))?.contains("a + b"));
    assert_cargo_test_passes(&sandbox_root);

    Ok(())
}

#[test]
fn rejected_patch_is_reverted_inside_sandbox() -> Result<()> {
    let repo = tiny_broken_rust_repo("verified-patch-rejected");
    let sandbox = GitWorktreeSandbox::create(repo.root())?;
    let sandbox_root = sandbox.root().to_path_buf();

    let model = ScriptedModel {
        actions: vec![Action::ApplyPatch(Patch {
            unified_diff: bad_zero_patch(),
        })],
    };
    let mut agent = Agent::builder()
        .model(model)
        .execution(LocalExecution::new(&sandbox_root))
        .language_adapter(RustAdapter::default())
        .indexer(BasicIndexer::new(&sandbox_root))
        .verifier(PlanVerifier)
        .policy(cargo_policy())
        .max_steps(1)
        .try_build()?;

    let report = agent.solve(TaskSpec::code_change(
        sandbox_root.clone(),
        "Fix the failing add test with the smallest correct patch.",
    ))?;

    assert_eq!(report.status, SolveStatus::BudgetExhausted);
    assert_eq!(report.attempts.len(), 1);
    assert_eq!(
        report.attempts[0].verification.status,
        VerificationStatus::Rejected
    );
    assert!(fs::read_to_string(sandbox_root.join("src/lib.rs"))?.contains("a - b"));

    Ok(())
}

fn tiny_broken_rust_repo(name: &str) -> TempRepo {
    let repo = TempRepo::new(name);
    repo.write(
        "Cargo.toml",
        r#"[package]
name = "tiny_add"
version = "0.1.0"
edition = "2021"

[dependencies]
"#,
    );
    repo.write(
        "Cargo.lock",
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "tiny_add"
version = "0.1.0"
"#,
    );
    repo.write(
        "src/lib.rs",
        r#"pub fn add(a: i32, b: i32) -> i32 {
    a - b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn add_returns_sum() {
        assert_eq!(add(2, 3), 5);
    }
}
"#,
    );
    repo.commit_all("seed broken rust crate");
    repo
}

fn correct_add_patch() -> String {
    r#"diff --git a/src/lib.rs b/src/lib.rs
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,5 +1,5 @@
 pub fn add(a: i32, b: i32) -> i32 {
-    a - b
+    a + b
 }
 
 #[cfg(test)]
"#
    .to_owned()
}

fn bad_zero_patch() -> String {
    r#"diff --git a/src/lib.rs b/src/lib.rs
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,5 +1,5 @@
 pub fn add(a: i32, b: i32) -> i32 {
-    a - b
+    0
 }
 
 #[cfg(test)]
"#
    .to_owned()
}

fn cargo_policy() -> Policy {
    Policy::ProjectConfiguredCommands {
        allowed_programs: vec!["cargo".to_owned()],
    }
}

fn assert_cargo_test_passes(root: &Path) {
    let output = Command::new("cargo")
        .arg("test")
        .current_dir(root)
        .output()
        .expect("cargo test should run");

    assert!(
        output.status.success(),
        "cargo test failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
